JB_A0=config\\importdata\\etl\\workingday.fmt
JB_A1=config\\importdata\\etl\\custindv.fmt
JB_A2=config\\importdata\\etl\\custcorp.fmt
JB_A3=config\\importdata\\etl\\custbank.fmt
JB_A4=config\\importdata\\etl\\tradefinance.fmt
JB_A5=config\\importdata\\etl\\bill.fmt
JB_A6=config\\importdata\\etl\\jsh.fmt
JB_A7=config\\importdata\\etl\\guarantee.fmt
JB_A8=config\\importdata\\etl\\loan.fmt
JB_A9=config\\importdata\\etl\\deposit.fmt
JB_A10=config\\importdata\\etl\\trandetail.fmt
JB_A11=config\\importdata\\etl\\acccust.fmt
JB_A13=config\\importdata\\etl\\accgl.fmt
JB_A14=config\\importdata\\etl\\limit.fmt
JB_A15=config\\importdata\\etl\\capital.fmt
JB_A16=config\\importdata\\etl\\exchangerate.fmt
JB_A16_2=config\\importdata\\etl\\exchangerateftz.fmt
JB_A17=config\\importdata\\etl\\tradefinancesec.fmt
JB_A18=config\\importdata\\etl\\custrelation.fmt
JB_A18_2=config\\importdata\\etl\\parnrelation.fmt
JB_A20=config\\importdata\\etl\\fixedmm.fmt
JB_A8_1=config\\importdata\\etl\\factoring.fmt