################UAT环境###################
#sourcepath=smb\://administrator\:Ab123456@10.130.24.7/jb/
#filepath=D\:\\T24DATAUAT\\SOURCEFILE\\
#logpath=D\:\\T24DATAUAT\\log\\
#history=D\:\\T24DATAUAT\\Backup\\
#errorfile=D\:\\T24DATAUAT\\ErrorFile\\
#kettelfilepath=D\:\\T24DATAUAT\\KettelFile\\
################生产环境##################
#sourcepath=smb\://JBUser\:Ab123456@10.129.0.39/jb_out/
#sourcepath=smb\://thinkpad\:1234rewq@Lenovo-pc/JB/
sourcepath=smb\://administrator\:Ab123456@10.130.24.27/JB/
#sourcepath=smb\://hadoop\:hadoop@10.128.100.149/smb2/
filepath=D\:\\T24DATA\\SOURCEFILE\\
logpath=D\:\\T24DATA\\log\\
history=D\:\\T24DATA\\Backup\\
errorfile=D\:\\T24DATA\\ErrorFile\\
kettelfilepath=D\:\\T24DATA\\KettelFile\\
reportwarnfilepath=D\:\\T24DATA\\warn\\
reportwarnbakfilepath=D\:\\T24DATA\\warnbak\\