#1-境外收入-福费廷					--->F
1=F
#2-境外收入-出口保理					--->T
2=T
#3-境外收入-出口押汇 				--->N
3=N
#4-境外收入-出口贴现					--->D
4=D
#5-境外收入-其它					--->O
5=O
#6-境内收入-深加工结转				--->M
5=M
#7-境内收入-保税区					--->X
7=X
#8-境内收入-出口加工区				--->E
8=E
#9-境内收入-钻石交易所				--->D
9=D
#10-境内收入-其他特殊经济区 			--->A
10=A
#11-境内收入-汇路引起出口项下跨境收入	--->R
11=R
#12-境内收入-出口信用保险理赔			--->C
12=C
#13-境内收入-出口货物保险理赔			--->I
13=I
#14-境内收入-买方信贷				--->N
14=N
#15-境内收入-转让信用证				--->L
15=L
#16-境内收入-背对背信用证 			--->B
16=B
#17-境内收入-其它 					--->O
17=O