#A-境外汇款预付货款		--->A
A=A
#B-境外汇款货到付款 		--->P
B=P
#C-境外汇款退款			--->R
C=R
#D-境外汇款其它			--->O
D=O
#E-境内汇款预付货款		--->A
E=A
#F-境内汇款货到付款		--->P
F=P
#G-境内汇款退款			--->R
G=R
#H-境内汇款其它			--->O
H=O
#I-对外付款预付货款		--->A
I=A
#J-对外付款其它			--->O
J=O
#K-境内付款预付货款		--->A
K=A
#L-境内付款其它			--->O
L=O