WORKINGDAY=JB_A0
CUSTINDV=JB_A1
CUSTCORP=JB_A2
CUSTBANK=JB_A3
TRADEFINANCE=JB_A4
BILL=JB_A5
JSH=JB_A6
GUARANTEE=JB_A7
LOAN=JB_A8
DEPOSIT=JB_A9
TRANDETAIL=JB_A10
ACCCUST=JB_A11
ACCGL=JB_A13
LIMIT=JB_A14
CAPITAL=JB_A15
EXCHANGERATE=JB_A16
EXCHANGERATEFTZ=JB_A16_2
TRADEFINANCESEC=JB_A17
CUSTRELATION=JB_A18
PARNRELATION=JB_A18_2
FIXEDMM=JB_A20
FACTORING=JB_A8_1