#mysql 
#########UAT环境#########
#diver_name=com.mysql.jdbc.Driver
#url=jdbc:mysql://10.130.24.51:3306/cubods?useUnicode=true&characterEncoding=UTF-8
#username=root
#password=cathay
#database_name=cubods
#######生产环境#######
diver_name=com.mysql.jdbc.Driver
url=jdbc:mysql://localhost:3306/cubods?useUnicode=true&characterEncoding=UTF-8
username=root
password=root
database_name=cubods

#oracle
#diver_name=oracle.jdbc.driver.OracleDriver
#url=jdbc:oracle:thin:@192.168.0.199:1521:jeecg
#username=jeecg
#password=jeecg
#database_name=jeecg

#postgre
#diver_name=org.postgresql.Driver
#url=jdbc:postgresql://localhost:5432/jeecg
#username=postgres
#password=postgres
#database_name=jeecg

